version = 0.1

[default.deploy.parameters]
stack_name = "s3-app-control"
s3_prefix = "s3-app-control"
parameter_overrides = "Stage=\"dev\", "
confirm_changeset = false
resolve_s3 = true
region = "us-west-2"
force-upload = true
capabilities = "CAPABILITY_IAM"

[prod.deploy.parameters]
stack_name = "app-control-149536470593"
s3_prefix = "app-control-149536470593"
parameter_overrides = "Stage=\"prod\""
confirm_changeset = true
resolve_s3 = true
region = "us-west-2"
force-upload = true
capabilities = "CAPABILITY_IAM"
