version = 1.0

[default.deploy.parameters]
stack_name = "cognito-gg-dev"
resolve_s3 = true
s3_prefix = "cognito-gg-dev"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""

[prod.deploy.parameters]
stack_name = "cognito-gg-prod"
resolve_s3 = true
s3_prefix = "cognito-gg-prod"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""
