version = 0.1

[default.deploy.parameters]
stack_name = "dev-ddb-users"
s3_prefix = "dev-ddb-users"
parameter_overrides = "Stage=\"dev\""
confirm_changeset = false
resolve_s3 = true
region = "us-west-2"
force-upload = true
capabilities = "CAPABILITY_IAM"

[prod.deploy.parameters]
stack_name = "ddb-users"
s3_prefix = "ddb-users"
parameter_overrides = "Stage=\"prod\""
confirm_changeset = true
resolve_s3 = true
region = "us-west-2"
force-upload = true
capabilities = "CAPABILITY_IAM"
