AWSTemplateFormatVersion: 2010-09-09
Description: DDB - users
Parameters:
  TableName:
    Type: String
    Default: users
  Stage:
    Type: String
    Default: dev

Resources:
  UsersDdb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email        # GSI
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: by_email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Env
          Value: !Ref Stage

Outputs:
  UsersTableExport:
    Description: Users table name
    Value: !Ref UsersDdb
    Export:
      Name: !Sub ddb-${TableName}
