AWSTemplateFormatVersion: 2010-09-09
Description: DDB - items (static catalog)
Parameters:
  TableName:
    Type: String
    Default: items
  Stage:
    Type: String
    Default: dev

Resources:
  ItemsDdb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: item_id
          AttributeType: S
      KeySchema:
        - AttributeName: item_id
          KeyType: HASH
      Tags:
        - Key: Env
          Value: !Ref Stage

Outputs:
  ItemsTableExport:
    Description: Items table name
    Value: !Ref ItemsDdb
    Export:
      Name: !Sub ddb-${TableName}
